# -*- coding: utf-8 -*-
"""dummy_config.py
"""
# config.py

DEEPLAKE_API_TOKEN = "INSERT-YOUR-API-KEY-HERE"
GOOGLE_API_KEY = "INSERT-YOUR-API-KEY-HERE"
OPENAI_API_KEY = "INSERT-YOUR-API-KEY-HERE"
PINECONE_API_KEY = "INSERT-YOUR-API-KEY-HERE"
HF_TOKEN = "INSERT-YOUR-API-KEY-HERE"
KAGGLE_KEY = "INSERT-YOUR-API-KEY-HERE"
KAGGLE_USERNAME = "INSERT-YOUR-USERNAME-HERE"
NGROK_API_KEY = "INSERT-YOUR-API-KEY-HERE"
PDF_CHARSPLITTER_CHUNKSIZE = 1000
PDF_CHARSPLITTER_CHUNK_OVERLAP = 100
CACHE_THRESHOLD = 0.5
